### ISSUE TITLE
What is LTER?

### ISSUE THREAD

**Issue by njtierney** [njlyon0/lterpalettefinder#5]
Hi there!

This package looks really neat! But I couldn't easily find what LTER stood for, and searching it online brought me back to your GH site - just wondering if there's a link or acronym you could share on the README page perhaps?

**Comment by njlyon0** [comment]
Thanks for pointing this out! LTER stands for Long Term Ecological Research (see our website here: [lternet.edu](https://lternet.edu/)) but that should definitely have been included in our documentation!

LTER is now defined in the following places:
1. README
2. `palette_find` function documentation
3. `pkgdown` website (linked in repo website field)
