### ISSUE TITLE
Sample error for simple image

### ISSUE THREAD

**Issue by SungManhin** [njlyon0/lterpalettefinder#6]
When extract colours in simple image like [origin image's link](https://i.328888.xyz/2022/12/31/nsx0Q.png)
`pic_palette <- palette_extract(image = "image_above.png", progress_bar = FALSE)`
return error
`Error in sample.int(m, k) : 
  cannot take a sample larger than the population when 'replace = FALSE'`
maybe the built-in `sample` module in the package sets a relatively large number to sample colours.

**Comment by njlyon0** [comment]
Thank you for bringing this to our attention!

Would you mind attaching the image you got this error with to this issue directly? I think you are correct about the source of the error and it should be a simple fix so I'll get on that right away.

**Comment by SungManhin** [comment]
I have already attached the image's link in the first comment, is it convenient to open the link? [the origin image's link](https://i.328888.xyz/2022/12/31/nsx0Q.png)

**Comment by njlyon0** [comment]
Ah, thanks for pointing that out. I'll use that image to re-create and then solve this issue

**Comment by njlyon0** [comment]
## Fixed!

I've tweaked the `palette_extract` function to successfully handle images of fewer than the minimum number of colors. I'm attaching the extracted palettes from your test image (thanks for that by the way!) as supporting evidence that it's fixed.

Note that you may need to re-install the development version of `lterpalettefinder` then quit and re-open RStudio in order for the necessary change to `palette_extract` to register on your local machine.

![simple_palette](https://user-images.githubusercontent.com/21199610/212126918-c3b76630-202d-46ff-9bdb-d632f3aa6c64.jpg)

---

You can reinstall the development version as follows:
```
# install.packages("devtools")
devtools::install_github("lter/lterpalettefinder")
```
