### ISSUE TITLE
Hex-code transformation 

### ISSUE THREAD

**Issue by SungManhin** [njlyon0/lterpalettefinder#7]
Thanks for fixing the last issue! 

Today I updated the package and trid to extract color from the simple [image](https://raw.githubusercontent.com/lter/lterpalettefinder/main/troubleshooting/simple_image.png), and I got this for `palette <- palette_extract(image = "simple_image.png", progress_bar = FALSE); palette`

`"#dc11"   "#8511"   "#ffdb89" "#fff6c3"`

3rd and 4th strings are colors in hex formats; but 1st and 2nd seems not...

Then I read the `palette_extract.R` and found in **line 88-91**, colors in 3 channel are put to integers, then they are transformed into hex-mode in **line 94-97**. At last these hex-class variables are transformed into characters and are pasted into a hex vector in **line 101-104**. This might cause problems. For rgb formats `rgb(220, 1, 1)`, red, green and blue integers will be transformed into hex-mode by `as.hexmode()` as `'dc', '1', '1'`, finally it is **"#dc11"**, but not the correct one **"#dc0101"**.

**Comment by njlyon0** [comment]
Happy to help and thanks for pointing this one out as well!

However, I can't reproduce that issue. When I run `palette_extract` on the test image I get correct hexadecimals. What version of R are you using?

Regardless this should still be doable to implement a fix for but I'm curious how I'm not getting that problem given that you are and your logic for why the issue would happen makes total sense to me

**Comment by njlyon0** [comment]
Interesting further complication:

It looks like `base::as.hexmode` changes the number of digits based on whether any numbers in the vector would require two digits. If the vector is entirely integers that become one-decimal hexadecimals (i.e., 1 - 15) then the resulting vector is one character per integer.

```
small_int <- base::as.integer(x = 1:15)
base::as.hexmode(x = small_int)
# [1] "1" "2" "3" "4" "5" "6" "7" "8" "9" "a" "b" "c" "d" "e" "f"
```

If, however, some of those integers are expressed as two hexadecimal digits, all of the integers are displayed as two digits.

```
lrg_int <- base::as.integer(x = 1:25)
base::as.hexmode(x = lrg_int)
# [1] "01" "02" "03" "04" "05" "06" "07" "08" "09" "0a" "0b" "0c" "0d" "0e" "0f" "10" "11"
# [18] "12" "13" "14" "15" "16" "17" "18" "19"
```

**Comment by njlyon0** [comment]
Discovered that the difference is due to R version. Previously I was using R ver `4.1.2` but when I updated to `4.2.2` I now get malformed hex codes due to improper `as.hexmode` functioning (or possibly `as.character` effect on hexmode objects).

Will begin debugging now.

## Edit

It is `as.character` operating incorrectly on `as.hexmode` object! Fixing is easier now that source of problem is identified

**Comment by njlyon0** [comment]
## Fix Implemented

Hi @SungManhin , I think I've fixed the issue but would you mind re-installing the development version of this package and trying again? Updating my R caused the same malformed hexcode on my computer that it did on yours and I've fixed the functions to avoid that but I want to be 100% certain that fix solved it for you as well

**Comment by SungManhin** [comment]
I'm sorry for not offering information of R environment... Yeah I'm using R 4.2.2 for a couple of months. (Also it's night hour in eastern China for the past few hours and I was unable to catch the comments :(  )

After updating the package it worked pretty fine for me! I tried many other images and all worked well. 😀

`lterpalettefinder` is really a helpful package: I always want to find a tool in R for extracting colors from images and present them in a tidy way; and it satisfied my demand. I'd like to keep using the package and offer my suggestions. Thanks a lot! 🎉🎉🎉

**Comment by njlyon0** [comment]
I'm so glad that the update fixed the problem for you and that you're finding the package helpful!!
